# Generated by Django 4.2.13 on 2024-11-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
