# Generated by Django 4.2.13 on 2024-11-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_address_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrequest',
            name='verified',
        ),
    ]
